displayName=Explorer's Compass
author=Strnger
support=https://github.com/Strnger/explorers-compass
description=Points a compass arrow to the nearest agility shortcut you can use but haven't discovered yet. Great for exploring content you're eligible for.
tags=agility,shortcut,explore,discovery,compass,arrow,navigation,poi,travel
plugins=com.explorerscompass.ExplorersCompassPlugin
build=standard
